name: ATCS
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7.5
  - pip=20.2.4
  - pytorch=1.6.0
  - torchvision=0.7.0
  - pip:
    - pytorch-lightning==1.0.3
    - torchtext==0.6.0
    - seaborn==0.11.0
    - tensorboard==2.3.0
    - tabulate==0.8.7
    - tqdm==4.50.2
    - pillow==8.0.1
    - spacy==2.3.0
    - pandas==1.1.3
    - transformers
    - datasets
    - sklearn
    - higher==0.2.1
    - nltk==3.6.2
    - emoji==1.2.0
    - jsonl
